// This file is auto-generated at build time. Do not edit manually.
export const KIT_IMAGES_FILES: string[] = [];
export const KITSIMAGES_FILES: string[] = [
  "alldoctorkits.png",
  "architechkit3.jpeg",
  "architectkit.png",
  "architectkitcontent.png",
  "budgetarchitectkit.png",
  "budgetempluyeeonboardingkit.png",
  "budgetmasonkit.png",
  "builderkit.png",
  "cementdealerbudgetkit.png",
  "cementdealergeneralkit.png",
  "cementdealerpremiumkit.png",
  "contractorkit.png",
  "dealerkit.png",
  "dealerkitwithcontent.png",
  "differentpacking.jpeg",
  "diwalibudgethamper.png",
  "diwaligeneralhamper.png",
  "diwalihamper.png",
  "diwalipremiumhamper.png",
  "doctorbudgetkit.png",
  "doctorgeneralkit.png",
  "doctorkit1.png",
  "doctorkit2.png",
  "doctorkit3.png",
  "doctorkitcontent.png",
  "electriciankit.png",
  "electriciankit1.png",
  "engineerkit.png",
  "engineerkit1.png",
  "engineerkit2.png",
  "engineerkitcontent.png",
  "generalarchitectkit.png",
  "generalemployeeonboardingkit.png",
  "generalmasonkit.png",
  "holibudgethamper.png",
  "holikit.png",
  "holipremiumhamper.png",
  "hospitalstaffkit.png",
  "hospitalstaffkit1.png",
  "interiordesignerkit.png",
  "kitsall.png",
  "masonkit.png",
  "masonkit2.png",
  "masonkit3.png",
  "masonkit4.jpeg",
  "newjoinerkit.png",
  "newjoinerkitcontent.png",
  "painterbudgetkit.png",
  "paintergeneralkit.png",
  "painterpremiumkit.png",
  "plumberkit.png",
  "plumberkit1.png",
  "plumberkitcontent.png",
  "premiumarchitectkit.png",
  "premiumdoctorkit.png",
  "premiumemployeeonboardingkit.png",
  "premiummasonkit.png",
  "womendaybudgethamper.png",
  "womendayhamper.png",
  "womendaypremiumhamper.png"
];
export const BUDGET_IMAGES_MAP: Record<string, string[]> = {
  "0-250": [],
  "250-500": [],
  "500-1000": [],
  "1000-2500": [],
  "2500-5000": [],
  "5000+": []
};
