/**
 * Centralized slug resolver for Kits & Hampers subcategories.
 * Maps legacy/URL kit query values to the canonical MongoDB subcategory slugs.
 */
export const getCanonicalKitSlug = (slug: string | null | undefined): string | undefined => {
  if (!slug) return undefined;
  
  const clean = slug.toLowerCase().replace(/[^a-z0-9]/g, "");
  
  // Corporate Kits mapping
  if (clean === "joining" || clean === "joiningkits") return "joining-kits";
  if (clean === "dealer" || clean === "dealerkits" || clean === "retailer" || clean === "retailerkits") return "dealer-kits";
  if (clean === "doctor" || clean === "doctorkits") return "doctor-kits";
  if (clean === "architect" || clean === "architectkits") return "architect-kits";
  if (clean === "mason" || clean === "masonkits") return "mason-kits";
  if (clean === "electrician" || clean === "electriciankits") return "electrician-kits";
  if (clean === "interiordesigner" || clean === "interiordesignerkit" || clean === "interiordesignerkits") return "interior-designer-kits";
  if (clean === "plumber" || clean === "plumberkits") return "plumber-kits";
  if (clean === "painter" || clean === "painterkits") return "painter-kits";
  if (clean === "engineer" || clean === "engineerkits") return "engineer-kits";
  
  // Festive Hampers mapping
  if (clean === "diwali" || clean === "diwalihampers") return "diwali-hampers";
  if (clean === "holi" || clean === "holihampers") return "holi-hampers";
  if (clean === "eid" || clean === "eidkits" || clean === "eidhampers") return "eid-kits";
  if (
    clean === "womens" ||
    clean === "womensday" ||
    clean === "womensdaygifts" ||
    clean === "womensdaygift" ||
    clean === "womensdayhampers" ||
    clean === "womensdayhamper" ||
    clean === "womenday" ||
    clean === "womendaygifts" ||
    clean === "womendaygift" ||
    clean === "womendayhampers" ||
    clean === "womendayhamper" ||
    clean === "woman" ||
    clean === "womansdaygifts" ||
    clean === "womansdaygift" ||
    clean === "womandaygifts" ||
    clean === "womandaygift" ||
    clean === "womensgifts" ||
    clean === "womensgift" ||
    clean === "internationalwomensday" ||
    clean === "iwd"
  ) return "womens-day-gifts";
  if (clean === "christmas" || clean === "christmaskits" || clean === "christmashampers") return "christmas-kits";
  if (clean === "newyear" || clean === "newyearhampers" || clean === "newyeargifts") return "new-year-hampers";
  
  // Default to returning the slug itself or appending suffix if it matches known patterns
  return slug;
};

/**
 * Centralized function to format and clean product titles.
 * Removes autogenerated prefixes/suffixes, random numbers, and internal identifiers.
 */
export const toSingularKitName = (name: string | null | undefined): string => {
  if (!name) return "";
  let str = name.trim();
  if (str.endsWith(" Kits")) {
    return str.substring(0, str.length - 1);
  }
  if (str.endsWith(" kits")) {
    return str.substring(0, str.length - 1);
  }
  return str;
};

export const cleanProductTitle = (title: string | null | undefined, fallbackName?: string): string => {
  if (!title) return fallbackName || "";
  const trimmed = title.trim();
  if (trimmed.startsWith("PacMyProduct")) {
    if (fallbackName) return fallbackName;
    return "Corporate Gift";
  }
  
  return trimmed
    .replace(/\s*\(\d+\)$/gi, "")
    .replace(/\s*copy$/gi, "")
    .replace(/\s+sub(?:\s+\d+|\s+-\s+\d+|\b)/gi, "")
    .replace(/\s+sub\s*-\s*\d+$/gi, "")
    .replace(/\s+sub\s+\d+$/gi, "")
    .replace(/[-_]\s*\d+$/g, "")
    .replace(/\s+\d+$/g, "")
    .trim();
};

/**
 * Centralized category slug resolver.
 * Maps dynamic/database category slug variations to the canonical slugs.
 */
export const getCanonicalCategorySlug = (slug: string | null | undefined): string => {
  if (!slug) return "";
  const clean = slug.toLowerCase().replace(/[^a-z0-9]/g, "");
  
  if (clean === "bags" || clean === "backpacksbags" || clean === "backpackbags") {
    return "bags";
  }
  if (
    clean === "diaries" ||
    clean === "diariesnotebooks" ||
    clean === "executivediaries" ||
    clean === "executivediary" ||
    clean === "econotebooks" ||
    clean === "econotebook" ||
    clean === "premiumnotebooks" ||
    clean === "premiumnotebook" ||
    clean === "notebooks" ||
    clean === "notebook"
  ) {
    return "diaries-notebooks";
  }
  if (
    clean === "tabletop" ||
    clean === "tabletopitems" ||
    clean === "paperweight" ||
    clean === "paperweightsub" ||
    clean === "mousepad" ||
    clean === "mousepadsub" ||
    clean === "deskorganiser" ||
    clean === "deskorganizer" ||
    clean === "deskorganisersub" ||
    clean === "deskorganizersub" ||
    clean === "tablemats" ||
    clean === "tablemat" ||
    clean === "tablematssub" ||
    clean === "desktopaccessories" ||
    clean === "desktopaccessoriessub"
  ) {
    return "table-top";
  }
  if (
    clean === "pens" ||
    clean === "pen" ||
    clean === "premiumpens" ||
    clean === "ecopens" ||
    clean === "plasticpens" ||
    clean === "metalpens" ||
    clean === "executivepens"
  ) {
    return "pens";
  }
  if (
    clean === "caps" ||
    clean === "cap" ||
    clean === "cottoncaps" ||
    clean === "sportscaps" ||
    clean === "promotionalcaps" ||
    clean === "baseballcaps"
  ) {
    return "caps";
  }
  if (clean === "badges" || clean === "badge") {
    return "badges";
  }
  if (clean === "neckrestbackrest" || clean === "neckrest" || clean === "backrest" || clean === "neckbackrest") {
    return "neck-rest-back-rest";
  }
  if (clean === "electronics" || clean === "electronic") {
    return "electronics";
  }
  if (clean === "decoratives" || clean === "decorative") {
    return "household-utilities";
  }
  if (clean === "householdutilities" || clean === "householdutility" || clean === "household") {
    return "household-utilities";
  }
  if (clean === "clocks" || clean === "clock") {
    return "clocks";
  }
  if (clean === "groomingkits" || clean === "groomingkit" || clean === "grooming") {
    return "grooming-kits";
  }
  if (clean === "executivekits" || clean === "executivekit" || clean === "executive") {
    return "executive-kits";
  }
  
  return slug;
};

/**
 * Centralized category name resolver.
 * Maps dynamic/database category names to their canonical display names.
 */
export const getCanonicalCategoryName = (name: string | null | undefined): string => {
  if (!name) return "";
  const clean = name.toLowerCase().replace(/[^a-z0-9]/g, "");
  
  if (clean === "bags" || clean === "backpacksbags" || clean === "backpackbags") {
    return "Bags";
  }
  if (
    clean === "diaries" ||
    clean === "diariesnotebooks" ||
    clean === "executivediaries" ||
    clean === "executivediary" ||
    clean === "econotebooks" ||
    clean === "econotebook" ||
    clean === "premiumnotebooks" ||
    clean === "premiumnotebook" ||
    clean === "notebooks" ||
    clean === "notebook"
  ) {
    return "Diaries / Notebooks";
  }
  if (
    clean === "tabletop" ||
    clean === "tabletopitems" ||
    clean === "paperweight" ||
    clean === "paperweightsub" ||
    clean === "mousepad" ||
    clean === "mousepadsub" ||
    clean === "deskorganiser" ||
    clean === "deskorganizer" ||
    clean === "deskorganisersub" ||
    clean === "deskorganizersub" ||
    clean === "tablemats" ||
    clean === "tablemat" ||
    clean === "tablematssub" ||
    clean === "desktopaccessories" ||
    clean === "desktopaccessoriessub"
  ) {
    return "Table Top";
  }
  if (
    clean === "pens" ||
    clean === "pen" ||
    clean === "premiumpens" ||
    clean === "ecopens" ||
    clean === "plasticpens" ||
    clean === "metalpens" ||
    clean === "executivepens"
  ) {
    return "Pens";
  }
  if (
    clean === "caps" ||
    clean === "cap" ||
    clean === "cottoncaps" ||
    clean === "sportscaps" ||
    clean === "promotionalcaps" ||
    clean === "baseballcaps"
  ) {
    return "Caps";
  }
  if (clean === "badges" || clean === "badge") {
    return "Badges";
  }
  if (clean === "neckrestbackrest" || clean === "neckrest" || clean === "backrest" || clean === "neckbackrest") {
    return "Neck Rest / Back Rest";
  }
  if (clean === "electronics" || clean === "electronic") {
    return "Electronics";
  }
  if (clean === "decoratives" || clean === "decorative") {
    return "Household Utilities";
  }
  if (clean === "householdutilities" || clean === "householdutility") {
    return "Household Utilities";
  }
  if (clean === "clocks" || clean === "clock") {
    return "Clocks";
  }
  if (clean === "groomingkits" || clean === "groomingkit" || clean === "grooming") {
    return "Grooming Kits";
  }
  if (clean === "executivekits" || clean === "executivekit" || clean === "executive") {
    return "Executive Kits";
  }
  
  return name;
};

/**
 * Centralized subcategory slug resolver.
 * Maps dynamic/database subcategory slug variations to the canonical slugs.
 */
export const getCanonicalSubcategorySlug = (slug: string | null | undefined): string => {
  if (!slug) return "";
  const clean = slug.toLowerCase().replace(/[^a-z0-9]/g, "");
  
  if (clean === "dealer" || clean === "dealerkits" || clean === "retailer" || clean === "retailerkits") {
    return "dealer-kits";
  }
  
  // Bags subcategories
  if (clean === "laptopbackpack" || clean === "laptopbackpacks" || clean === "laptopbag" || clean === "laptopbags") {
    return "laptop-bags";
  }
  if (clean === "travelbackpack" || clean === "travelbackpacks" || clean === "travelbag" || clean === "travelbags") {
    return "travel-bags";
  }
  if (clean === "duffelbag" || clean === "duffelbags" || clean === "dufflebag" || clean === "dufflebags" || clean === "duffel" || clean === "duffle") {
    return "duffle-bags";
  }
  if (clean === "trolleybag" || clean === "trolleybags" || clean === "canvastrolleybag" || clean === "canvastrolleybags" || clean === "canvastrolley") {
    return "trolley-bags";
  }
  if (clean === "slingbag" || clean === "slingbags") {
    return "sling-bags";
  }
  if (clean === "conferencebag" || clean === "conferencebags") {
    return "conference-bags";
  }
  if (clean === "totebag" || clean === "totebags") {
    return "tote-bags";
  }

  // Caps subcategories
  if (
    clean === "caps" || clean === "cap" || clean === "cottoncaps" || clean === "cottoncap" ||
    clean === "sportscaps" || clean === "sportscap" || clean === "promotionalcaps" || clean === "promotionalcap" ||
    clean === "baseballcaps" || clean === "baseballcap" || clean === "eventcaps" || clean === "eventcap" ||
    clean === "snapbackcaps" || clean === "snapbackcap"
  ) {
    return "caps";
  }

  // Paper Weight subcategories
  if (clean === "paperweight" || clean === "paperweightsub") {
    return "paper-weight";
  }

  // Table Top subcategories
  if (
    clean === "tabletop" || clean === "tabletopitems" || clean === "tabletopitem" ||
    clean === "mousepad" || clean === "mousepadsub" || clean === "mousepads" ||
    clean === "deskorganiser" || clean === "deskorganizersub" || clean === "deskorganisers" || clean === "deskorganizer" || clean === "deskorganizersub" || clean === "deskorganizers" ||
    clean === "tablemat" || clean === "tablematssub" || clean === "tablemats" ||
    clean === "desktopaccessories" || clean === "desktopaccessoriesitems" || clean === "desktopaccessoriesitem" || clean === "desktopaccessoriessub"
  ) {
    return "table-top";
  }

  // Pens
  if (
    clean === "pens" || clean === "pen" || clean === "premiumpens" || clean === "premiumpen" ||
    clean === "ecopens" || clean === "ecopen" || clean === "plasticpens" || clean === "plasticpen" ||
    clean === "metalpens" || clean === "metalpen" || clean === "executivepens" || clean === "executivepen" ||
    clean === "engravedpens" || clean === "engravedpen" || clean === "giftboxpens" || clean === "giftboxpen"
  ) {
    return "pens";
  }

  // Diaries / Notebooks
  if (
    clean === "diaries" || clean === "diariesnotebooks" || clean === "diariesnotebook" ||
    clean === "executivediaries" || clean === "executivediary" ||
    clean === "econotebooks" || clean === "econotebook" ||
    clean === "premiumnotebooks" || clean === "premiumnotebook" ||
    clean === "notebooks" || clean === "notebook" ||
    clean === "premiumdiaries" || clean === "premiumdiary" ||
    clean === "standardnotebooks" || clean === "standardnotebook"
  ) {
    return "diaries-notebooks";
  }

  // Festive Hampers
  if (clean === "diwali" || clean === "diwalihampers") return "diwali-hampers";
  if (clean === "holi" || clean === "holihampers") return "holi-hampers";
  if (clean === "eid" || clean === "eidkits" || clean === "eidhampers") return "eid-kits";
  if (
    clean === "womens" ||
    clean === "womensday" ||
    clean === "womensdaygifts" ||
    clean === "womensdaygift" ||
    clean === "womensdayhampers" ||
    clean === "womensdayhamper" ||
    clean === "womenday" ||
    clean === "womendaygifts" ||
    clean === "womendaygift" ||
    clean === "womendayhampers" ||
    clean === "womendayhamper" ||
    clean === "woman" ||
    clean === "womansdaygifts" ||
    clean === "womansdaygift" ||
    clean === "womandaygifts" ||
    clean === "womandaygift" ||
    clean === "womensgifts" ||
    clean === "womensgift" ||
    clean === "internationalwomensday" ||
    clean === "iwd"
  ) return "womens-day-gifts";
  if (clean === "christmas" || clean === "christmaskits" || clean === "christmashampers") return "christmas-kits";
  if (clean === "newyear" || clean === "newyearhampers" || clean === "newyeargifts") return "new-year-hampers";

  // Badges & Neck Rest
  if (clean === "badges" || clean === "badge" || clean === "badgessub" || clean === "badgesub") return "badges-sub";
  if (clean === "neckrestbackrest" || clean === "neckrest" || clean === "backrest" || clean === "neckbackrest" || clean === "neckrestbackrestsub") return "neck-rest-back-rest-sub";

  // Electronics & Clocks & Grooming & Executive
  if (clean === "wireless" || clean === "wirelesscharger" || clean === "wirelesschargers") return "wireless-charger";
  if (clean === "decorative" || clean === "decoratives") return "decorative";
  if (clean === "householdutilities" || clean === "householdutility" || clean === "household" || clean === "wired" || clean === "bluetoothspeaker" || clean === "bluetoothspeakers" || clean === "speaker" || clean === "speakers") return "household-utilities";
  if (clean === "wallclock" || clean === "wallclocks") return "wall-clock";
  if (clean === "wristwatch" || clean === "wristwatches" || clean === "watch" || clean === "watches") return "wrist-watch";
  if (clean === "malegroomingkit" || clean === "malegroomingkits" || clean === "malegrooming") return "male-grooming-kit";
  if (clean === "femalegroomingkit" || clean === "femalegroomingkits" || clean === "femalegrooming") return "female-grooming-kit";
  if (clean === "executivekits" || clean === "executivekit" || clean === "executivekitssub" || clean === "executivekitsub") return "executive-kits-sub";

  return slug;
};

/**
 * Centralized subcategory name resolver.
 * Maps dynamic/database subcategory names to their canonical display names.
 */
export const getCanonicalSubcategoryName = (name: string | null | undefined): string => {
  if (!name) return "";
  const clean = name.toLowerCase().replace(/[^a-z0-9]/g, "");

  if (
    clean === "dealerkits" ||
    clean === "dealer" ||
    clean === "retailerkits" ||
    clean === "retailer" ||
    clean === "dealerretailerkit" ||
    clean === "dealerretailerkits" ||
    clean === "dealerkit"
  ) {
    return "Dealer / Retailer Kit";
  }
  if (clean === "doctorkits" || clean === "doctorkit" || clean === "doctor") {
    return "Doctor Kits";
  }
  if (clean === "engineerkits" || clean === "engineerkit" || clean === "engineer") {
    return "Engineer Kits";
  }
  if (clean === "architectkits" || clean === "architectkit" || clean === "architect") {
    return "Architect Kits";
  }
  if (clean === "masonkits" || clean === "masonkit" || clean === "mason") {
    return "Mason Kits";
  }
  if (clean === "electriciankits" || clean === "electriciankit" || clean === "electrician") {
    return "Electrician Kits";
  }
  if (clean === "interiordesignerkits" || clean === "interiordesignerkit" || clean === "interiordesigner") {
    return "Interior Designer Kits";
  }
  if (clean === "plumberkits" || clean === "plumberkit" || clean === "plumber") {
    return "Plumber Kits";
  }
  if (clean === "painterkits" || clean === "painterkit" || clean === "painter") {
    return "Painter Kits";
  }
  if (clean === "joiningkits" || clean === "joiningkit" || clean === "joining") {
    return "Joining Kits";
  }
  if (clean === "diwalihampers" || clean === "diwalihamper" || clean === "diwali") {
    return "Diwali Hampers";
  }
  if (clean === "holihampers" || clean === "holihamper" || clean === "holi") {
    return "Holi Hampers";
  }
  if (clean === "eidkits" || clean === "eidkit" || clean === "eid" || clean === "eidhampers") {
    return "Eid Hampers";
  }
  if (
    clean === "womensdaygifts" || clean === "womensdaygift" || clean === "womensday" ||
    clean === "womendaygifts" || clean === "womenday" || clean === "iwd"
  ) {
    return "Women's Day Gifts";
  }
  if (clean === "christmaskits" || clean === "christmaskit" || clean === "christmas" || clean === "christmashampers") {
    return "Christmas Hampers";
  }
  if (clean === "newyearhampers" || clean === "newyearhamper" || clean === "newyear") {
    return "New Year Hampers";
  }
  if (clean === "festivehampers" || clean === "festivehamper") {
    return "Festive Hampers";
  }

  // Bags subcategories
  if (clean === "laptopbackpack" || clean === "laptopbackpacks" || clean === "laptopbag" || clean === "laptopbags") {
    return "Laptop Bags";
  }
  if (clean === "travelbackpack" || clean === "travelbackpacks" || clean === "travelbag" || clean === "travelbags") {
    return "Travel Bags";
  }
  if (clean === "duffelbag" || clean === "duffelbags" || clean === "dufflebag" || clean === "dufflebags" || clean === "duffel" || clean === "duffle") {
    return "Duffle Bags";
  }
  if (clean === "trolleybag" || clean === "trolleybags" || clean === "canvastrolleybag" || clean === "canvastrolleybags") {
    return "Trolley Bags";
  }
  if (clean === "slingbag" || clean === "slingbags") {
    return "Sling Bags";
  }
  if (clean === "conferencebag" || clean === "conferencebags") {
    return "Conference Bags";
  }
  if (clean === "totebag" || clean === "totebags") {
    return "Tote Bags";
  }

  // Caps subcategories
  if (
    clean === "caps" || clean === "cap" || clean === "cottoncaps" || clean === "cottoncap" ||
    clean === "sportscaps" || clean === "sportscap" || clean === "promotionalcaps" || clean === "promotionalcap" ||
    clean === "baseballcaps" || clean === "baseballcap" || clean === "eventcaps" || clean === "eventcap" ||
    clean === "snapbackcaps" || clean === "snapbackcap"
  ) {
    return "Caps";
  }

  // Paper Weight subcategories
  if (clean === "paperweight" || clean === "paperweightsub") {
    return "Paper Weight";
  }

  // Table Top subcategories
  if (
    clean === "tabletop" || clean === "tabletopitems" || clean === "tabletopitem" ||
    clean === "mousepad" || clean === "mousepadsub" || clean === "mousepads" ||
    clean === "deskorganiser" || clean === "deskorganizersub" || clean === "deskorganisers" || clean === "deskorganizer" || clean === "deskorganizersub" || clean === "deskorganizers" ||
    clean === "tablemat" || clean === "tablematssub" || clean === "tablemats" ||
    clean === "desktopaccessories" || clean === "desktopaccessoriesitems" || clean === "desktopaccessoriesitem" || clean === "desktopaccessoriessub"
  ) {
    return "Table Top";
  }

  // Pens subcategories
  if (
    clean === "pens" || clean === "pen" || clean === "premiumpens" || clean === "premiumpen" ||
    clean === "ecopens" || clean === "ecopen" || clean === "plasticpens" || clean === "plasticpen" ||
    clean === "metalpens" || clean === "metalpen" || clean === "executivepens" || clean === "executivepen" ||
    clean === "engravedpens" || clean === "engravedpen" || clean === "giftboxpens" || clean === "giftboxpen"
  ) {
    return "Pens";
  }

  // Diaries / Notebooks
  if (
    clean === "diaries" || clean === "diariesnotebooks" || clean === "diariesnotebook" ||
    clean === "executivediaries" || clean === "executivediary" ||
    clean === "econotebooks" || clean === "econotebook" ||
    clean === "premiumnotebooks" || clean === "premiumnotebook" ||
    clean === "notebooks" || clean === "notebook" ||
    clean === "premiumdiaries" || clean === "premiumdiary" ||
    clean === "standardnotebooks" || clean === "standardnotebook"
  ) {
    return "Diaries / Notebooks";
  }

  // Festive Hampers
  if (clean === "diwali" || clean === "diwalihampers") return "Diwali Hampers";
  if (clean === "holi" || clean === "holihampers") return "Holi Hampers";
  if (clean === "eid" || clean === "eidkits" || clean === "eidhampers") return "Eid Kits";
  if (
    clean === "womens" ||
    clean === "womensday" ||
    clean === "womensdaygifts" ||
    clean === "womensdaygift" ||
    clean === "womensdayhampers" ||
    clean === "womensdayhamper" ||
    clean === "womenday" ||
    clean === "womendaygifts" ||
    clean === "womendaygift" ||
    clean === "womendayhampers" ||
    clean === "womendayhamper" ||
    clean === "woman" ||
    clean === "womansdaygifts" ||
    clean === "womansdaygift" ||
    clean === "womandaygifts" ||
    clean === "womandaygift" ||
    clean === "womensgifts" ||
    clean === "womensgift" ||
    clean === "internationalwomensday" ||
    clean === "iwd"
  ) return "Women's Day Gifts";
  if (clean === "christmas" || clean === "christmaskits" || clean === "christmashampers") return "Christmas Kits";
  if (clean === "newyear" || clean === "newyearhampers" || clean === "newyeargifts") return "New Year Hampers";

  // Badges & Neck Rest Name Mappings
  if (clean === "badges" || clean === "badge" || clean === "badgessub" || clean === "badgesub") return "Badges";
  if (clean === "neckrestbackrest" || clean === "neckrest" || clean === "backrest" || clean === "neckbackrest" || clean === "neckrestbackrestsub") return "Neck Rest / Back Rest";

  // Electronics & Clocks & Grooming & Executive Name Mappings
  if (clean === "wireless" || clean === "wirelesscharger" || clean === "wirelesschargers") return "Wireless";
  if (clean === "decorative" || clean === "decoratives") return "Decorative";
  if (clean === "householdutilities" || clean === "householdutility" || clean === "wired" || clean === "bluetoothspeaker" || clean === "bluetoothspeakers" || clean === "speaker" || clean === "speakers") return "Household Utilities";
  if (clean === "wallclock" || clean === "wallclocks") return "Wall Clock";
  if (clean === "wristwatch" || clean === "wristwatches" || clean === "watch" || clean === "watches") return "Wrist Watch";
  if (clean === "malegroomingkit" || clean === "malegroomingkits" || clean === "malegrooming") return "Male Grooming Kit";
  if (clean === "femalegroomingkit" || clean === "femalegroomingkits" || clean === "femalegrooming") return "Female Grooming Kit";
  if (clean === "executivekits" || clean === "executivekit" || clean === "executivekitssub" || clean === "executivekitsub") return "Executive Kits";

  return name;
};

/**
 * Centralized category slug aliases.
 * Returns all equivalent database category slugs for a given category slug.
 */
export const getCategorySlugAliases = (slug: string | null | undefined): string[] => {
  if (!slug) return [];
  const canon = getCanonicalCategorySlug(slug);
  if (canon === "bags") {
    return ["bags", "backpacks-bags", "backpack-bags"];
  }
  if (canon === "diaries-notebooks") {
    return ["diaries-notebooks", "diaries", "executive-diaries", "eco-notebooks", "premium-notebooks", "notebooks"];
  }
  if (canon === "table-top") {
    return ["table-top", "tabletop", "paper-weight", "mouse-pad", "desk-organiser", "table-mats", "desktop-accessories", "paperweight", "mousepad", "deskorganiser", "tablemat"];
  }
  if (canon === "pens") {
    return ["pens", "premium-pens", "eco-pens", "plastic-pens", "metal-pens", "executive-pens"];
  }
  if (canon === "caps") {
    return ["caps", "cotton-caps", "sports-caps", "promotional-caps", "baseball-caps"];
  }
  if (canon === "household-utilities") {
    return ["household-utilities", "householdutilities", "householdutility", "household-utility", "decoratives", "decorative"];
  }
  return [slug, canon].filter((v, i, a) => a.indexOf(v) === i);
};

/**
 * Centralized subcategory slug aliases.
 * Returns all equivalent database subcategory slugs for a given subcategory slug.
 */
export const getSubcategorySlugAliases = (slug: string | null | undefined): string[] => {
  if (!slug) return [];
  const canon = getCanonicalSubcategorySlug(slug);
  
  if (canon === "dealer-kits" || canon === "retailer-kits" || slug === "dealer-kits" || slug === "retailer-kits") {
    return ["dealer-kits", "retailer-kits"];
  }
  
  if (canon === "laptop-bags") {
    return ["laptop-bags", "laptop-backpacks"];
  }
  if (canon === "travel-bags") {
    return ["travel-bags", "travel-backpacks"];
  }
  if (canon === "duffle-bags") {
    return ["duffle-bags", "duffel-bags", "duffel-bag", "duffle-bag"];
  }
  if (canon === "canvas-trolley-bags" || canon === "trolley-bags") {
    return ["canvas-trolley-bags", "trolley-bags", "canvastrolleybag", "canvastrolleybags", "trolleybag", "trolleybags", "canvas trolley bags", "canvas trolley bag", "trolley bag", "trolley bags"];
  }
  if (canon === "sling-bags") {
    return ["sling-bags", "slingbag", "slingbags"];
  }
  if (canon === "pens") {
    return ["pens", "premium-pens", "eco-pens", "plastic-pens", "metal-pens", "executive-pens", "gift-box-pens", "engraved-pens", "premiumpens", "ecopens", "plasticpens", "metalpens", "executivepens"];
  }
  if (canon === "caps") {
    return ["caps", "promotional-caps", "sports-caps", "cotton-caps", "baseball-caps", "event-caps", "snapback-caps", "promotionalcaps", "sportscaps", "cottoncaps", "baseballcaps"];
  }
  if (canon === "table-top") {
    return [
      "table-top", "tabletop", "mouse-pad", "desk-organiser", "table-mats", "mousepad", "deskorganiser", "tablemat", 
      "desktop-accessories", "desktopaccessories", "desktopaccessoriessub"
    ];
  }
  if (canon === "diaries-notebooks") {
    return [
      "diaries-notebooks", "diaries", "executive-diaries", "premium-diaries", "eco-notebooks", "standard-notebooks", 
      "diariesnotebooks", "executivediary", "econotebook", "premiumnotebooks", "notebooks", "notebook"
    ];
  }
  if (canon === "paper-weight" || canon === "paper-weight-sub") {
    return ["paper-weight", "paperweight", "paper-weight-sub", "paperweightsub"];
  }
  if (canon === "wireless-charger") {
    return ["wireless-charger", "wireless", "wirelesscharger", "wireless-chargers"];
  }
  if (canon === "household-utilities") {
    return ["household-utilities", "household", "householdutilities"];
  }
  if (canon === "eid-kits") {
    return ["eid-kits", "eid-hampers", "eidhampers", "eidkits", "eid"];
  }
  if (canon === "christmas-kits") {
    return ["christmas-kits", "christmas-hampers", "christmashampers", "christmaskits", "christmas"];
  }
  if (canon === "bluetooth-speaker") {
    return ["bluetooth-speaker", "wired", "bluetoothspeaker", "bluetoothspeakers", "speaker", "speakers"];
  }
  if (canon === "decorative") {
    return ["decorative", "decoratives"];
  }
  return [slug, canon].filter((v, i, a) => a.indexOf(v) === i);
};

/**
 * Shared helper to resolve product display name based on priority:
 * Display Name -> Subcategory -> Title -> Name -> Category
 */
export const resolveDisplayName = (product?: {
  title?: string;
  name?: string;
  displayName?: string;
  category?: string;
  subcategory?: string;
}): string => {
  if (!product) return "";
  const subcatName = product.subcategory ? getCanonicalSubcategoryName(product.subcategory) : "";
  
  if (product.displayName && product.displayName.trim() !== "" && !product.displayName.trim().startsWith("PacMyProduct")) {
    return cleanProductTitle(product.displayName, subcatName);
  }
  if (product.title && product.title.trim() !== "" && !product.title.trim().startsWith("PacMyProduct")) {
    return cleanProductTitle(product.title, subcatName);
  }
  if (product.name && product.name.trim() !== "" && !product.name.trim().startsWith("PacMyProduct")) {
    return cleanProductTitle(product.name, subcatName);
  }
  if (subcatName) {
    return subcatName;
  }
  if (product.category && product.category.trim() !== "") {
    return getCanonicalCategoryName(product.category);
  }
  
  return "Corporate Gift";
};

/**
 * Legacy classification helper to check if a product represents a Paper Weight.
 * Priority order:
 * 1. Explicit displayName
 * 2. Product title
 * 3. Product name
 * 4. Tags
 * 5. Existing helper utilities (slug)
 */
export const isPaperWeightProduct = (product: any): boolean => {
  if (!product) return false;

  // Priority 1: Explicit display name
  if (product.displayName && typeof product.displayName === "string") {
    const dn = product.displayName.toLowerCase();
    if (dn.includes("paper weight") || dn.includes("paperweight")) return true;
  }

  // Priority 2: Product title
  if (product.title && typeof product.title === "string") {
    const t = product.title.toLowerCase();
    if (t.includes("paper weight") || t.includes("paperweight")) return true;
  }

  // Priority 3: Product name
  if (product.name && typeof product.name === "string") {
    const n = product.name.toLowerCase();
    if (n.includes("paper weight") || n.includes("paperweight")) return true;
  }

  // Priority 4: Tags
  if (Array.isArray(product.tags)) {
    if (
      product.tags.some(
        (tag: any) =>
          typeof tag === "string" &&
          (tag.toLowerCase().includes("paper weight") || tag.toLowerCase().includes("paperweight"))
      )
    ) {
      return true;
    }
  }

  // Priority 5: Existing helper utilities (slug check)
  if (product.slug && typeof product.slug === "string") {
    const s = product.slug.toLowerCase();
    if (s.includes("paper-weight") || s.includes("paperweight")) return true;
  }

  return false;
};



